### ISSUE TITLE
IFileDialog::SetOptions

### ISSUE THREAD

**Issue by rednoah** [dbwiddis/IFileDialogImp#2]
I've added the `FILEOPENDIALOGOPTIONS` enum constants for the [`IFileDialog::SetOptions`](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-ifiledialog-setoptions) method here:
* https://github.com/rednoah/IFileDialogImp/blob/main/test/FILEOPENDIALOGOPTIONS.java

I'd do a pull request but you probably know better how to integrate enum constants into jna-platform APIs.

**Comment by dbwiddis** [comment]
You did it exactly the way it's normally done. The only question is in which file to put them.  Generally a filename matching the header filename works.  I'll add these shortly.

**Comment by dbwiddis** [comment]
Merged in 409e2b3773999e777a31957cebbb3d538264080f
