### ISSUE TITLE
SHCreateItemFromParsingName 

### ISSUE THREAD

**Issue by rednoah** [dbwiddis/IFileDialogImp#3]
Looks like I will also need a binding for `SHCreateItemFromParsingName ` so I can create an `IShellItem` so I can call `IFileDialog::setDefaultFolder`:
* https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-ifiledialog-setdefaultfolder
* https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-shcreateitemfromparsingname

**Comment by dbwiddis** [comment]
Added in f2e08908e438c03d83d5c55f4bd239d18c248e58
